### ISSUE TITLE
macOS Monterey issue

### ISSUE THREAD

**Issue by svobluk** [littlebrighter/alfred--ultimate-currency-converter#4]
Hi, it looks like there is some problem with the latest macOS Monterey. I'm getting this within debug - ERROR: Ultimate Currency Converter[Script Filter] Code 127: /bin/bash: php: command not found

**Comment by dexamenos** [comment]
Hi @svobluk – thanks for pointing this out.

Apple made some changes in Monterey, one being: `php` no longer ships with the OS. You have to install it on your own in order to be able to continue to use this workflow (and many other workflows, I guess). 

I recommend installing `php` with `homebrew`, see this link for a starting point https://brew.sh/

However, there have been some additional things, that needed to be addressed. I hope, v1.12.0 works for you with Monterey. If not, please let me know. https://github.com/littlebrighter/alfred--ultimate-currency-converter/releases/tag/v1.12.0

**Comment by dexamenos** [comment]
Honestly, I did not test with PHP8 so far. 

Having done so now: apparently, some _notices_ turned into _warnings_, which the new release should now handle properly. https://github.com/littlebrighter/alfred--ultimate-currency-converter/releases/tag/v1.12.1

Please let us know, if it works for you, now.

**Comment by svobluk** [comment]
> Honestly, I did not test with PHP8 so far.
> 
> Having done so now: apparently, some _notices_ turned into _warnings_, which the new release should now handle properly. https://github.com/littlebrighter/alfred--ultimate-currency-converter/releases/tag/v1.12.1
> 
> Please let us know, if it works for you, now.

Works great now, thanks a lot!

**Comment by Wookbert** [comment]
> Works great now, thanks a lot!

Don't forget to [tip the author](https://www.paypal.me/n8g1) via PayPal. 3 Euros for a beer or 8 Euros for Pizza are always welcome... 🍺🍕🙃

**Comment by dexamenos** [comment]
@svobluk good to hear. **Thanks** a lot. Feel free to address any further issues (or ideas for possible future features)
